language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      env: CMAKE_OPTIONS="-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DOPENGL_ENABLED=OFF -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres -DQt5Core_DIR=/opt/qt54/lib/cmake/Qt5Core -DQt5OpenGL_DIR=/opt/qt54/lib/cmake/Qt5OpenGL" QT_QPA_PLATFORM=offscreen
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - build-essential
    - os: osx
      env: CMAKE_OPTIONS="-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DIPO_ENABLED=OFF -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DQt5Core_DIR=/usr/local/opt/qt5/lib/cmake/Qt5Core -DQt5OpenGL_DIR=/usr/local/opt/qt5/lib/cmake/Qt5OpenGL"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps
    - ${TRAVIS_BUILD_DIR}/build

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science
      brew install \
        cmake \
        glew || true
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3

      sudo add-apt-repository --yes ppa:beineri/opt-qt542-trusty
      sudo apt-get update -qq 
      sudo apt-get -y install doxygen doxygen-doc doxygen-latex doxygen-gui graphviz

      
      cd ${TRAVIS_BUILD_DIR}
    fi

script:
  - cmake --version
  - cd build
  - |
    if [[ -z "$(ls -A Svar)" ]]; then
      git clone https://github.com/zdzhaoyong/Svar.git
    fi
  - cd Svar
  - git checkout ${TRAVIS_BRANCH}
  - git pull
  - mkdir -p build
  - cd build
  - pwd
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DTESTS_ENABLED=ON ${CMAKE_OPTIONS}
  - make -j2
  - ../bin/svar -tests
  
# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
